# action.yml
name: 'go_sdl2-actionbuilder'
description: 'Git action builder to crossplatform building (OSX, LINUX and WINDOWS) with go_sdl2 (https://github.com/veandco/go-sdl2)'
inputs:
  gosdl2-version:
    description: 'gosdl2 version to use in Docker (docker image: FROM ymohlcl/gosdl2:<gosdl2-version>)'
    required: false
    default: 'latest'
  docker-context:
    description: 'path to the context to forward at go_sdl2_builder docker'
    required: false
    default: '.'
  artifact-name:
    description: 'folder name to push on the following workflow (ex: binaries file)'
    required: false
    default: 'bin'
  path-workdir:
    description: 'workdir path to the default sharing volume from github action'
    required: false
    default: '/github/workspace'
  docker-name:
    description: 'docker name to the container resulting from the build'
    required: false
    default: 'go_sdl2_actionbuilder'
  docker-volume:
    description: 'docker volume name used by the go sdl2 builder container'
    required: false
    default: 'go_sdl2_actionbuilder-volume'
outputs:
  config:
    description: 'return the configuration to build the project'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gosdl2-version }}
    - ${{ inputs.docker-context }}
    - ${{ inputs.artifact-name }}
    - ${{ inputs.path-workdir }}
    - ${{ inputs.docker-name }}
    - ${{ inputs.docker-volume }}
branding:
  icon: 'box'  
  color: 'black'
